[workspace]
members = ["core", "cli"]
resolver = "2"

[workspace.package]
edition = "2024"
authors = ["Ed1th"]
readme = "README.md"
license = "GPL-3.0-or-later"

[workspace.dependencies]
log = "0.4.29"
env_logger = "0.11.8"
