[package]
name = "angrybirds-cryptor-cli"
version = "0.4.0"
edition = "2021"
authors = ["ed1th"]
description = "Command-line interface for Angry Birds file cryptor"
license = "GPL-3.0-or-later"

[dependencies]
clap = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
toml = { workspace = true }
angrybirds-cryptor-core = { path = "../core" }
